service:
  port: 8080

spring:
  application:
    name: ai-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:9092}
    consumer:
      group-id: ai-service
      auto-offset-reset: earliest

#dev
app:
  callback:
    url: ""
    enabled: false
  mode: polling

#prod
#app:
#  callback:
#    url: ${CALLBACK_URL:https://api.yourdomain.com/api/stt/webhook}
#    enabled: ${WEBHOOK_ENABLED:true}
#  mode: webhook

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true